openapi: 3
info:
  title: Steel Mill
  description": Tryna cop some free mild steel.
  version: 0.1.0
servers:
  - url: http://localhost:8000
paths:
  /api/hello:
    post:
      summary: Add Brewery to Bracket
      description: Adds a Brewery document to a Bracket Document's Breweries list.
      requestBody:
        content:
          application/json:
            schema:
              bracketId: string
              serializedBreweryJson: string
            example:
              bracketId: 1MdnmknrirwWZcqGf00h
              serializedBreweryJson:
                Name: Creature Comforts Brewing Company
                Description: ""
                Short_Description: ""
                Url: http://www.creaturecomfortsbeer.com/
                Facebook_Url: ""
                Twitter_Url: ""
                Instagram_Url: ""
                Address: 271 W Hancock Ave, Athens, GA 30601
                DocumentID: Exen63googSMVqRoTC2b
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
